# Generated by Django 4.2.10 on 2024-03-02 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('emp_code', models.IntegerField()),
                ('manager_code', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('approved', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('in_wait', 'in_wait')], default='in_wait', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('position', models.CharField(choices=[('employee', 'employee'), ('semi_manager', 'semi_manager'), ('leader', 'leader')], max_length=50)),
                ('salary', models.IntegerField()),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('browing_lim', models.IntegerField()),
                ('normal_vecation', models.IntegerField()),
                ('casual_vecation', models.IntegerField()),
                ('manager_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('salary', models.IntegerField()),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('browing_lim', models.IntegerField()),
                ('normal_vecation', models.IntegerField()),
                ('casual_vecation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vecation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vecation_type', models.CharField(choices=[('normal', 'normal'), ('casual', 'casual')], max_length=50)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('to_date', models.DateField()),
                ('emp_code', models.IntegerField()),
                ('manager_code', models.IntegerField()),
                ('approved', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('in_wait', 'in_wait')], default='in_wait', max_length=50)),
            ],
        ),
    ]
